import http                      from 'http';
import {dispatchFleetRequest}    from './dispatchFleetRequest.mjs';
import {createFleetIngressGuard} from './fleetIngressAuth.mjs';
import {
    createFleetWireResponse,
    FLEET_WIRE_RESPONSE_STATES
} from './fleetWireMethods.mjs';
import {isLocalBearerToken}      from '../../mcp/server/shared/helpers/localBearer.mjs';

/**
 * @summary Start the Node end of the Option-B (dev-server) app↔fleet transport: a minimal HTTP server
 * exposing the fleet control surface to the browser agentos app — behind the Fleet ingress trust
 * boundary. Every request passes {@link createFleetIngressGuard} (Host allowlist, exact cockpit
 * Origin policy, constant-time process-bearer check) BEFORE a single body byte is read or any method
 * name is looked at; every admitted `POST /fleet` then executes inside the injected request-context
 * runner with the SERVER-stamped viewer identity, so `MailboxService`-class admission checks read a
 * transport-authenticated fact and never a caller claim.
 *
 * Fail-closed at construction: no canonical bearer, no bound viewer identity, or no context runner →
 * the server refuses to start. Loopback reachability is not authentication; this module no longer has
 * an unauthenticated mode at all.
 *
 * CORS is exact-origin: the request's own Origin is echoed back ONLY after matching the configured
 * cockpit allowlist, always with `Vary: Origin`; the previous wildcard grant is gone. Preflights are
 * admitted on Host + Origin alone (they cannot carry `Authorization` by construction) and grant
 * nothing beyond the header echo that lets the real request present its bearer.
 *
 * `GET /fleet/probe` (bearer-gated like everything else) answers the one-command boot contract: it
 * names the bound viewer + process so a relauncher can prove "same token, same viewer" before
 * reusing an existing process — an unknown or mismatched process yields a named refusal upstream,
 * never silent reuse.
 *
 * Deliberately transport-swappable: the browser side only needs a sender for versioned Fleet
 * envelopes, so HTTP can be replaced by Electron's in-process injection without touching the pane.
 * `/fleet/probe` is an out-of-band launch receipt; every `/fleet` refusal or dispatch result uses
 * the finite C2 response vocabulary.
 *
 * @param {Object}   opts
 * @param {Number}   [opts.port=8083]            `0` selects an ephemeral port (tests).
 * @param {String}   [opts.host='127.0.0.1']     Loopback by default — never bind a public interface.
 * @param {Function} [opts.dispatch=dispatchFleetRequest] Injectable request router (a stub in tests).
 * @param {Number}   [opts.maxBodyBytes=1048576] Request-body cap; oversized bodies are dropped.
 * @param {String}   opts.bearerToken            Process-lifetime secret (canonical 32-byte unpadded
 *     base64url) — generated by the launch path, never persisted. REQUIRED.
 * @param {Object}   opts.viewerContext          The server-resolved viewer stamped onto every
 *     admitted request. REQUIRED with a bound `agentIdentityNodeId`; the transport never accepts a
 *     caller-supplied identity in its place.
 * @param {String}   opts.viewerContext.userId
 * @param {String}   [opts.viewerContext.username]
 * @param {String}   opts.viewerContext.agentIdentityNodeId
 * @param {Function} opts.runInContext           `(context, fn) => fn-result` — the production launch
 *     path passes `RequestContextService.run` so admission primitives downstream read the stamped
 *     viewer. REQUIRED: the server refuses to construct without a context boundary to execute in.
 * @param {String[]} [opts.allowedOrigins=['http://localhost:8080', 'http://127.0.0.1:8080']] Exact
 *     cockpit origins for the CORS policy.
 * @param {String[]} [opts.extraAllowedHosts=[]] Additional exact `Host` header values (the defaults
 *     always cover the bound host:port spellings).
 * @param {Boolean}  [opts.bearerHandshake=false] Arms `GET /fleet/handshake`: an exact-allowlisted
 *     browser Origin may redeem the process bearer, which is how the one-command cockpit hands the
 *     secret to a plain page with no agent seam (see the `fleet.bearerHandshake` leaf for the
 *     custody decision). Unarmed, the path stays inside the bearer-gated 404 surface.
 * @returns {Promise<http.Server>} resolves once the server is listening.
 * @throws {TypeError} When the bearer, viewer binding, or context runner is missing/invalid — the
 *     fail-closed startup contract of the ingress trust boundary.
 */
export function startFleetBridgeServer({
    port              = 8083,
    host              = '127.0.0.1',
    dispatch          = dispatchFleetRequest,
    maxBodyBytes      = 1024 * 1024,
    bearerToken       = null,
    viewerContext     = null,
    runInContext      = null,
    allowedOrigins    = ['http://localhost:8080', 'http://127.0.0.1:8080'],
    extraAllowedHosts = [],
    bearerHandshake   = false
} = {}) {
    if (!isLocalBearerToken(bearerToken)) {
        throw new TypeError('[fleet] startup refused: a canonical 32-byte unpadded-base64url bearerToken is required (fail-closed ingress)')
    }

    if (!viewerContext?.userId || !viewerContext?.agentIdentityNodeId) {
        throw new TypeError('[fleet] startup refused: a server-resolved viewerContext with userId + agentIdentityNodeId is required — the transport never trusts a caller-supplied identity')
    }

    if (typeof runInContext !== 'function') {
        throw new TypeError('[fleet] startup refused: runInContext is required so every admitted request executes inside the request-context boundary')
    }

    const startedAt = new Date().toISOString();

    // The bound port is only known after listen (ephemeral 0 in tests) — resolve Host values late.
    let boundPort = null;

    const admit = createFleetIngressGuard({
        bearerToken,
        allowedOrigins,
        bearerHandshake,
        resolveAllowedHosts() {
            const hosts = ['127.0.0.1', 'localhost', '[::1]']
                .map(name => boundPort === null ? null : `${name}:${boundPort}`)
                .filter(Boolean);

            return [...hosts, ...extraAllowedHosts]
        }
    });

    const respond = (res, status, payload, corsOrigin) => {
        const headers = {'Content-Type': 'application/json'};

        if (corsOrigin) {
            headers['Access-Control-Allow-Origin'] = corsOrigin;
            headers['Vary']                        = 'Origin'
        }

        res.writeHead(status, headers);
        res.end(JSON.stringify(payload))
    };

    const server = http.createServer((req, res) => {
        const decision = admit(req);

        // Refusal path: the body is never parsed or accumulated — the data listeners below are
        // never attached; `resume()` discards the stream at the socket layer so the refusal
        // response still delivers cleanly, and `Connection: close` stops keep-alive reuse of a
        // socket an unauthenticated caller could keep streaming into.
        if (!decision.admitted) {
            res.setHeader('Connection', 'close');
            respond(
                res,
                decision.status,
                createFleetWireResponse(FLEET_WIRE_RESPONSE_STATES.refused, {error: decision.error}),
                decision.corsOrigin
            );
            return req.resume()
        }

        if (decision.preflight) {
            const headers = {
                'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
                'Access-Control-Allow-Headers': 'Content-Type, Authorization'
            };

            if (decision.corsOrigin) {
                headers['Access-Control-Allow-Origin'] = decision.corsOrigin;
                headers['Vary']                        = 'Origin'
            }

            res.writeHead(204, headers);
            return res.end()
        }

        // The armed browser bearer handshake (guard step 3.5): the ONE response that carries the
        // secret — never cached, never keep-alive, logged as identity facts only (the redeeming
        // origin; the bearer itself stays out of every log line this process emits).
        if (decision.handshake) {
            console.log(`[fleet] bearer handshake redeemed by origin ${req.headers.origin} at ${new Date().toISOString()}`);
            res.setHeader('Connection', 'close');
            res.setHeader('Cache-Control', 'no-store');
            return respond(res, 200, {ok: true, result: {bearerToken}}, decision.corsOrigin)
        }

        // Exact-path match — a sibling path like /fleetx must fail closed, never reach dispatch.
        const {pathname} = new URL(req.url, 'http://127.0.0.1');

        // The boot/probe contract: an authenticated relauncher proves "same token, same viewer"
        // before reusing this process. Carries identity facts only — never the bearer itself.
        if (req.method === 'GET' && pathname === '/fleet/probe') {
            return respond(res, 200, {
                ok    : true,
                result: {
                    agentIdentityNodeId: viewerContext.agentIdentityNodeId,
                    userId             : viewerContext.userId,
                    pid                : process.pid,
                    startedAt
                }
            }, decision.corsOrigin)
        }

        if (req.method !== 'POST' || pathname !== '/fleet') {
            return respond(
                res,
                404,
                createFleetWireResponse(FLEET_WIRE_RESPONSE_STATES.refused, {error: 'fleet: POST /fleet only'}),
                decision.corsOrigin
            )
        }

        let body = '';

        req.on('data', chunk => {
            body += chunk;
            if (body.length > maxBodyBytes) req.destroy()
        });

        req.on('end', async () => {
            let request;

            try {
                request = JSON.parse(body || '{}')
            } catch {
                return respond(
                    res,
                    400,
                    createFleetWireResponse(FLEET_WIRE_RESPONSE_STATES.refused, {error: 'fleet: invalid JSON body'}),
                    decision.corsOrigin
                )
            }

            // The identity stamp: the SERVER's boot-resolved viewer, never anything the request
            // carried. Everything downstream (dispatch → bridge → MailboxService-class admission)
            // reads this context; a caller-authored identity field simply never enters the flow.
            // dispatch never throws (it returns a fail-closed envelope), but guard the transport
            // anyway — and never leak a raw error / stack to the client.
            let envelope;

            try {
                envelope = await runInContext({...viewerContext, source: 'fleet-ingress'}, () => dispatch(request))
            } catch (error) {
                console.error('[fleet] request dispatch threw:', error);
                envelope = createFleetWireResponse(FLEET_WIRE_RESPONSE_STATES.operationFailed, {
                    error: 'fleet: request failed'
                })
            }

            respond(res, 200, envelope, decision.corsOrigin)
        })
    });

    return new Promise((resolve, reject) => {
        server.on('error', reject);
        server.listen(port, host, () => {
            boundPort = server.address().port;
            resolve(server)
        })
    })
}
