import Base      from './Base.mjs';
import ApiParser from '../parser/ApiParser.mjs';
import fs        from 'fs-extra';
import path      from 'path';

/**
 * @summary Extracts knowledge chunks from JSDoc API data.
 *
 * This source provider reads the `docs/output/all.json` file generated by the JSDoc build process.
 * It delegates the parsing logic to `ApiParser` to convert the structured API data into
 * flat knowledge chunks suitable for vector embedding.
 *
 * This separation of concerns ensures that `DatabaseService` remains focused on orchestration,
 * while this class handles the specific logistics of locating and reading API documentation.
 *
 * @class Neo.ai.mcp.server.knowledge-base.source.ApiSource
 * @extends Neo.ai.mcp.server.knowledge-base.source.Base
 * @singleton
 */
class ApiSource extends Base {
    static config = {
        /**
         * @member {String} className='Neo.ai.mcp.server.knowledge-base.source.ApiSource'
         * @protected
         */
        className: 'Neo.ai.mcp.server.knowledge-base.source.ApiSource',
        /**
         * @member {String} apiPath='docs/output/all.json'
         */
        apiPath: 'docs/output/all.json',
        /**
         * @member {Boolean} singleton=true
         * @protected
         */
        singleton: true
    }

    /**
     * Extracts knowledge chunks from the JSDoc JSON output.
     * @param {Object}   writeStream  The JSONL write stream.
     * @param {Function} createHashFn Function to create content hash.
     * @returns {Promise<Number>} The number of chunks extracted.
     */
    async extract(writeStream, createHashFn) {
        let count = 0;
        const apiPath = path.resolve(process.cwd(), this.apiPath);

        if (await fs.pathExists(apiPath)) {
            const apiData = await fs.readJson(apiPath);
            const chunks  = ApiParser.parse(apiData);

            chunks.forEach(chunk => {
                chunk.hash = createHashFn(chunk);
                writeStream.write(JSON.stringify(chunk) + '\n');
                count++;
            });
        }

        return count;
    }
}

export default Neo.setupClass(ApiSource);
